; Template for project details
; Generated by Daniela from pom.xml version 0.0.3-SNAPSHOT
; on date 28/06/2018, time 12:37:52 PM

!define PROJECT_BASEDIR "..\..\"
!define PROJECT_BUILD_DIR "..\"
!define PROJECT_FINAL_NAME "SimpleTest-0.0.3-SNAPSHOT"
!define PROJECT_GROUP_ID "dmarino"
!define PROJECT_ARTIFACT_ID "SimpleTest"
!define PROJECT_NAME "Simple Test"
!define PROJECT_VERSION "0.0.3-SNAPSHOT"
; The project organization section is missing from your pom.xml
